site_name: Odin Documentation
site_url: https://getodin.cloud
site_description: Odin official documentation.
site_author: Benoit LEFEBVRE

repo_url: https://github.com/odin-oss/monolith-api
repo_name: GitHub

theme:
  name: material
  logo: images/logo.png
  favicon: images/favicon.ico
  palette: 
    # Light/Dark mode toggle (optional but recommended)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light green  # This changes the header color
      accent: light green   # This changes the color of links/buttons
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
        
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light green
      accent: light green
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

copyright: 'Copyright &copy; 2026 <a href="mailto:benlef99@gmail.com">Benoit LEFEBVRE</a> & the previous contributors.'

nav:
  - Home: index.md
  - Getting Started: presentation/index.md
  - Tutorials:
    - 1. How to set up my development environment: tutorials/1.how-to-set-up-my-development-environment.md
    - Environment:
      - How to deploy my own environment: tutorials/environment/how-to-deploy-my-own-environment.md
  - Contributors: contributors/index.md