site_name: Odin Documentation
site_url: https://odin.github.io/
repo_url: https://github.com/odin-oss/monolith-api
repo_name: GitHub

theme:
  name: material

nav:
  - Home: index.md
  - Getting Started: presentation/index.md
  - Tutorials: tutorials/index.md